### ISSUE TITLE
Cannot successfully compile remote-shuffle on master branch.

### ISSUE THREAD

**Issue by haojinIntel** [oap-project/remote-shuffle#30]
We try to build remote-shuffle on master branch with this command "mvn clean package -DskipTests" and meet the following issues:
![image](https://user-images.githubusercontent.com/44394375/122518608-01b62580-d044-11eb-82fc-739612f8e643.png)
The issue can be reproduced on several machines.

**Comment by haojinIntel** [comment]
@carsonwang @zhixingheyi-tian Please help to track the issue. Thanks!

**Comment by jiafuzha** [comment]
redeploy daos-java-1.2.1-SNAPSHOT
